# ============================================================
# CORE UI
# ============================================================

accent = "#d94a74"
cursor = "#FF9C3A"

foreground = "#CDD5ED"
background = "#101214"

selection_foreground = "#f6a3a9"
selection_background = "#262a2d"

# ============================================================
# TERMINAL COLORS (STRICT IMAGE SET)
# ============================================================

color0  = "#101214"
color1  = "#F66F9B"
color2  = "#91AFDE"
color3  = "#FDCED0"
color4  = "#C669C0"
color5  = "#FFAB77"
color6  = "#E6F1FF"
color7  = "#5A3C8A"

# ============================================================
# BRIGHTS
# ============================================================

color8  = "#262a2d"
color9  = "#e46a7a"
color10 = "#f6a3a9"
color11 = "#ff9c3a"
color12 = "#6b6ecf"
color13 = "#d94a74"
color14 = "#5a3c8a"
color15 = "#ffffff"
